// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FastaSequence = { identifier: string, sequence: string, };

export type NJConfig = { msa: Array<FastaSequence>, hide_internal: boolean, };
