// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SubstitutionModel } from "../../nj/bindings/SubstitutionModel";

/**
 * Full configuration for a single Neighbor-Joining run.
 *
 * Pass an `NJConfig` to [`crate::nj`] to run the algorithm and receive a
 * Newick string. The alphabet (DNA vs. protein) is auto-detected from the
 * sequences; [`substitution_model`](NJConfig::substitution_model) must be
 * compatible with that alphabet or an error is returned.
 */
export type NJConfig = { 
/**
 * The aligned sequences to build the tree from. All sequences must have
 * the same length.
 */
msa: Array<SequenceObject>, 
/**
 * Number of bootstrap replicates used to compute support values on
 * internal nodes. Set to `0` to skip bootstrapping entirely.
 */
n_bootstrap_samples: number, 
/**
 * Substitution model used to compute pairwise distances.
 */
substitution_model: SubstitutionModel, };

/**
 * A single sequence in a multiple sequence alignment.
 *
 * Both fields are plain `String`s so that the struct can be constructed
 * from any source (FASTA parser, JSON, Python dict) without encoding overhead.
 * The actual byte-level encoding into typed symbols is deferred to
 * [`crate::msa::MSA::push`].
 */
export type SequenceObject = { 
/**
 * Sequence name, e.g. the FASTA header without the leading `>`.
 */
identifier: string, 
/**
 * Raw sequence string, e.g. `"ACGT"` or `"ARND"`. Gap characters (`-`)
 * are preserved and handled by the substitution models.
 */
sequence: string, };
