// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Available substitution models.
 *
 * | Variant | Alphabet | Formula |
 * |---------|----------|---------|
 * | `PDiff` | DNA, Protein | `p` |
 * | `JukesCantor` | DNA only | `-0.75 · ln(1 - 4p/3)` |
 * | `Kimura2P` | DNA only | `-0.5 · ln(1-2p-q) - 0.25 · ln(1-2q)` |
 * | `Poisson` | Protein only | `-ln(1 - p)` |
 *
 * Model–alphabet compatibility is enforced at runtime in [`crate::nj`].
 */
export type SubstitutionModel = "PDiff" | "JukesCantor" | "Kimura2P" | "Poisson";
